### ISSUE TITLE
Is it possible to have a pytorch version?

### ISSUE THREAD

**Issue by veroveroxie** [fissoreg/relative-gradient-jacobian#1]
Hi,

Thanks for you great work!
I noticed that you used JAX as the framework. Is it possible to have a pytorch version of this?

Thanks!

**Comment by fissoreg** [comment]
Hey,

thanks for your interest!

In principle, there are no problems in implementing our method on top of PyTorch, and that's already on our TODO list. I'll look into it next week and get back here for updates :)

**Comment by sidml** [comment]
@fissoreg Any updates ?

**Comment by fissoreg** [comment]
Hi @sidml, thanks for your interest!

I don't really have any good excuses for the delay at this point, I'll try to prioritize this work and be sure that I will write here when the PyTorch implementation will be ready.

Thanks for the patience!

**Comment by fissoreg** [comment]
@veroveroxie @sidml sorry again for the delay!

Hoping this is still useful, the PyTorch version is now available.

Thanks for the patience!
